{% set name = "hist" %}
{% set version = "2.8.0" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hist-{{ version }}.tar.gz
  sha256: 0a3e602dd1d2721bd7f2229f456709dde323f6f74952f13ba4e5986c3275f77b

build:
  number: 2
  noarch: python

outputs:
  - name: hist-base
    build:
      noarch: python
      entry_points:
        - hist=hist.classichist:main
      # c.f. https://github.com/conda/grayskull/issues/582#issuecomment-2482370940
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - hatchling
        - hatch-vcs
      run:
        - boost-histogram >=1.3.1,<1.6
        - histoprint >=2.2
        - numpy >=1.14.5
        - python >={{ python_min }}
        # Actually only required for [py<311] but require for all Python versions so this can be noarch: python
        - typing-extensions

    test:
      imports:
        - hist
        - hist.axis
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: hist
    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage('hist-base', exact=True) }}
        # The plot requirements
        - matplotlib-base >=3.0
        - mplhep >=0.2.16
        # The fit plot requirements
        - scipy >=1.4
        - iminuit >=2.0

    test:
      imports:
        - hist
        - hist.axis
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

about:
  home: https://github.com/scikit-hep/hist
  summary: Hist classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://hist.readthedocs.io/
  dev_url: https://github.com/scikit-hep/hist

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - LovelyBuggies
