{% set name = "hist" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hist-{{ version }}.tar.gz
  sha256: 0a3e602dd1d2721bd7f2229f456709dde323f6f74952f13ba4e5986c3275f77b

build:
  number: 1
outputs:
  - name: hist-base
    build:
      noarch: python
      entry_points:
        - hist=hist.classichist:main
      script: python -m pip install . --no-deps -vv

    requirements:
      host:
        - pip
        - python >=3.8
        - hatchling
        - hatch-vcs
      run:
        - boost-histogram >=1.3.1,<1.6
        - histoprint >=2.2
        - numpy >=1.14.5
        - python >=3.7
        # Actually only required for [py<311] but require for all Python versions so this can be noarch: python
        - typing-extensions

    test:
      imports:
        - hist
        - hist.axis

  - name: hist
    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage('hist-base', exact=True) }}
        # The plot requirements
        - matplotlib-base >=3.0
        - mplhep >=0.2.16
        # The fit plot requirements
        - scipy >=1.4
        - iminuit >=2.0

    test:
      imports:
        - hist
        - hist.axis

about:
  home: https://github.com/scikit-hep/hist
  summary: Hist classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - LovelyBuggies
